Repository pavelzw/pixi-diff-to-markdown, pull requests merged in 2025-04, with the labels that each got.

#58 docs: Add download badge
  README.md
Labels: documentation

#57 handle missing version in git pypi dependencies
  pixi_diff_to_markdown/models.py
  pyproject.toml
  tests/resources/diff-example-v6-lockfile.json
  tests/resources/diff-example-v6-lockfile/merge-no_hide-no_change-type-False_explicit-False_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-no_change-type-False_explicit-False_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-no_change-type-False_explicit-True_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-no_change-type-False_explicit-True_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-no_change-type-True_explicit-False_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-no_change-type-True_explicit-False_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-no_change-type-True_explicit-True_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-no_change-type-True_explicit-True_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-yes_change-type-False_explicit-False_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-yes_change-type-False_explicit-False_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-yes_change-type-False_explicit-True_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-yes_change-type-False_explicit-True_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-yes_change-type-True_explicit-False_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-yes_change-type-True_explicit-False_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-yes_change-type-True_explicit-True_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-no_hide-yes_change-type-True_explicit-True_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-no_change-type-False_explicit-False_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-no_change-type-False_explicit-False_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-no_change-type-False_explicit-True_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-no_change-type-False_explicit-True_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-no_change-type-True_explicit-False_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-no_change-type-True_explicit-False_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-no_change-type-True_explicit-True_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-no_change-type-True_explicit-True_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-yes_change-type-False_explicit-False_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-yes_change-type-False_explicit-False_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-yes_change-type-False_explicit-True_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-yes_change-type-False_explicit-True_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-yes_change-type-True_explicit-False_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-yes_change-type-True_explicit-False_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-yes_change-type-True_explicit-True_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-split-explicit_hide-yes_change-type-True_explicit-True_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-no_change-type-False_explicit-False_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-no_change-type-False_explicit-False_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-no_change-type-False_explicit-True_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-no_change-type-False_explicit-True_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-no_change-type-True_explicit-False_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-no_change-type-True_explicit-False_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-no_change-type-True_explicit-True_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-no_change-type-True_explicit-True_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-yes_change-type-False_explicit-False_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-yes_change-type-False_explicit-False_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-yes_change-type-False_explicit-True_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-yes_change-type-False_explicit-True_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-yes_change-type-True_explicit-False_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-yes_change-type-True_explicit-False_package-type-True.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-yes_change-type-True_explicit-True_package-type-False.md
  tests/resources/diff-example-v6-lockfile/merge-yes_hide-yes_change-type-True_explicit-True_package-type-True.md
Labels: bug

#60 ci: Create release.yml
  .github/release.yml
Labels: ci

#63 fix: pydantic-settings 2.9.0 incompatibility
  pixi.lock
  pixi.toml
  pixi_diff_to_markdown/pydantic_settings_extension.py
  pyproject.toml
Labels: bug
